//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows;
    using System.Windows.Media;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.AdditionalImage = new HashSet<AdditionalImage>();
            this.ClientService = new HashSet<ClientService>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Duration { get; set; }
        public int Cost { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Description { get; set; }
        public string Discountstr
        {
            get
            {
                if(this.Discount > 0)
                {
                    return this.Discount.ToString() + "%";
                }
                else
                {
                    return "";
                }
            }
            set
            {
                this.Discountstr = value;
            }
        }
        public SolidColorBrush ItemBackground
        {
            get
            {
                if(this.Discount> 0)
                {
                    return new SolidColorBrush(Colors.LightGreen);
                }
                else
                {
                    return new SolidColorBrush(Colors.White);
                }
            }
            set
            {
                this.ItemBackground = value;
            }
        }
        public TextDecorationCollection TextDeco 
        {
            get
            {
                if(this.Discount> 0)
                {
                    return TextDecorations.Strikethrough;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TextDeco = value;
            }
        }
        public string NewCost
        {
            get
            {
                if(this.Discount > 0)
                {
                    return ((int)(this.Cost - this.Cost * (this.Discount / 100.0))).ToString();
                }
                else
                {
                    return "";
                }
            }
            set
            {
                this.NewCost = value;
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalImage> AdditionalImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
    }
}
